# generated by prepate_state.sh - DO NOT ADD ANYTHING HERE MANUALLY
terraform {
  backend "s3" {
    bucket         = "chuck-fanduel-dev-tf-state"
    key            = "chuck-fanduel"
    region         = "us-east-1"
    dynamodb_table = "chuck-fanduel-dev-state-tf-locks"
    encrypt        = true
    assume_role = {
      role_arn = "arn:aws:iam::442042513173:role/Terraform"
    }
  }
}
